import type { Metadata } from "next";
import "./globals.css";
import "ds-core/styles";
import { UniformContext } from '@uniformdev/canvas-next-rsc';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = "brand-1 light desktop default";
  return (
    <html lang="en">
      <body className={theme}>
        <UniformContext>
          {children}
        </UniformContext>
      </body>
    </html>
  );
}
